package(
    default_visibility = ["//visibility:private"],
)

android_binary(
  name = "dev",
  srcs = [
      "java"
  ],
  manifest = "AndroidManifest.xml",
  multidex = "native",
  shrink_resources = 1,
  resource_files = [
    "res"
  ]  
)
